#!/usr/bin/env node
// lib/migrate-config.js — Migrate metaswarm projects to tribunal format
// Usage: node migrate-config.js [project-dir]
// Outputs: JSON report to stdout

'use strict';

const fs = require('fs');
const path = require('path');

function migrate(projectDir) {
  const report = { created: [], renamed: [], skipped: [], errors: [] };

  const tribunalYaml = path.join(projectDir, 'tribunal.yaml');
  const coverageFile = path.join(projectDir, '.coverage-thresholds.json');
  const metaswarmDir = path.join(projectDir, '.metaswarm');
  const tribunalDir = path.join(projectDir, '.tribunal');
  const externalToolsFile = path.join(metaswarmDir, 'external-tools.yaml');

  // 1. Check if tribunal.yaml already exists — skip creation
  if (fs.existsSync(tribunalYaml)) {
    report.skipped.push('tribunal.yaml (already exists)');
  } else {
    // Read coverage thresholds if available
    let coverage = null;
    let enforcement = null;

    if (fs.existsSync(coverageFile)) {
      try {
        const raw = JSON.parse(fs.readFileSync(coverageFile, 'utf8'));
        if (raw.thresholds) coverage = raw.thresholds;
        if (raw.enforcement) enforcement = raw.enforcement;
      } catch (err) {
        report.errors.push(`Failed to parse ${coverageFile}: ${err.message}`);
      }
    }

    // Abort if coverage file was malformed
    if (report.errors.length > 0) {
      report.skipped.push('tribunal.yaml (skipped due to parse errors)');
      return report;
    }

    // Check for external-tools.yaml
    const hasExternalTools = fs.existsSync(externalToolsFile);

    // Generate tribunal.yaml
    const yamlLines = [];
    yamlLines.push('# tribunal.yaml — Generated by migrate-config.js');
    if (hasExternalTools) {
      yamlLines.push('# TODO: Review .metaswarm/external-tools.yaml and migrate settings manually');
    }
    yamlLines.push('');
    yamlLines.push('common:');

    // Coverage section
    if (coverage) {
      yamlLines.push('  coverage:');
      if (coverage.lines != null) yamlLines.push(`    lines: ${coverage.lines}`);
      if (coverage.branches != null) yamlLines.push(`    branches: ${coverage.branches}`);
      if (coverage.functions != null) yamlLines.push(`    functions: ${coverage.functions}`);
      if (coverage.statements != null) yamlLines.push(`    statements: ${coverage.statements}`);
    }

    // Enforcement section (camelCase → snake_case)
    if (enforcement) {
      yamlLines.push('  enforcement:');
      if (enforcement.command != null) {
        const escaped = String(enforcement.command).replace(/'/g, "''");
        yamlLines.push(`    command: '${escaped}'`);
      }
      if (enforcement.blockPRCreation != null) yamlLines.push(`    block_pr_creation: ${enforcement.blockPRCreation}`);
      if (enforcement.blockTaskCompletion != null) yamlLines.push(`    block_task_completion: ${enforcement.blockTaskCompletion}`);
    }

    // Default sections
    yamlLines.push('  debate:');
    yamlLines.push('    rounds: 2');
    yamlLines.push('    agents:');
    yamlLines.push('      - architect');
    yamlLines.push('      - security');
    yamlLines.push('      - cto');
    yamlLines.push('    allow_extra_round: true');
    yamlLines.push('  agent_selection:');
    yamlLines.push('    strategy: scored');
    yamlLines.push('    decay_days: 14');
    yamlLines.push('  escalation:');
    yamlLines.push('    enabled: true');
    yamlLines.push('    threshold: 3');
    yamlLines.push('  health_check:');
    yamlLines.push('    enabled: true');
    yamlLines.push('    interval: 300');
    yamlLines.push('');

    fs.writeFileSync(tribunalYaml, yamlLines.join('\n'), 'utf8');
    report.created.push('tribunal.yaml');
  }

  // 2. Rename .metaswarm/ to .tribunal/
  if (fs.existsSync(metaswarmDir)) {
    if (fs.existsSync(tribunalDir)) {
      report.skipped.push('.tribunal/ (already exists)');
    } else {
      try {
        fs.renameSync(metaswarmDir, tribunalDir);
        report.renamed.push('.metaswarm/ → .tribunal/');
      } catch (err) {
        report.errors.push(`Failed to rename .metaswarm/: ${err.message}`);
      }
    }
  }

  return report;
}

// --- CLI entry point ---
if (require.main === module) {
  const projectDir = process.argv[2] || process.cwd();

  if (!fs.existsSync(projectDir) || !fs.statSync(projectDir).isDirectory()) {
    console.error(`Error: not a valid directory: ${projectDir}`);
    process.exit(1);
  }

  const report = migrate(projectDir);
  console.log(JSON.stringify(report, null, 2));

  if (report.errors.length > 0) {
    process.exit(1);
  }
}

module.exports = { migrate };
